# Generated by Django 6.0.4 on 2026-06-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="failedemail",
            name="error_message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="failedemail",
            name="exhausted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="failedemail",
            index=models.Index(
                condition=models.Q(
                    ("exhausted_at__isnull", True), ("success_at__isnull", True)
                ),
                fields=["next_retry_at"],
                name="failedemail_pending_idx",
            ),
        ),
    ]
